### PR TITLE
hardcode elementary theme

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
bot, build

**Comment by nedrichards** [comment]
next step, make a list of other elementary apps on flathub that we should similarly patch/engage with upstream on.

**Comment by bil-elmoussaoui** [comment]
bot, build

**Comment by nedrichards** [comment]
Er, this didn't build. https://flathub.org/builds/#/builders/41/builds/4

**Comment by TingPing** [comment]
Copy pasted the extension prefix instead of the /app prefix.

**Pull request merged**
