### PR TITLE
update to v1.1.0

### LINKED ISSUE #4: Remove GLib patch
I fixed the issue with a non-present constant on master: https://github.com/donadigo/appeditor/commit/bdf596f287d31554b2131af4ef9e76f5c6924ab3, so that the patch here can be removed.

### LINKED ISSUE #6: Appeditor Installed from flatpak on flathub cannot see my menu entries #50
This bug is from  https://github.com/donadigo/appeditor/issues/50#issuecomment-384021409

I guess there is some sandboxing that stops it editing my menus ?

image

It only sees a minimal menu with itself on it.

OS is Ubuntu 18.04.

App was installed from the Ubuntu Software app, but on flatpak.

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Fixes #6 
Fixes #4 
Fixes https://github.com/donadigo/appeditor/issues/40
Fixes https://github.com/donadigo/appeditor/issues/50

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
@TingPing Hey, sorry to ping you here. I have fixed the issues related to not seeing all desktop files. Somehow GLib or the app itself shows only the desktop files that have a valid Exec (the binary should be found somewhere). When I have added `/run/host/usr/bin` to `$PATH` it seems to work but only if I open the application from a terminal. Otherwise, it doesn't show up at all...Do you have any idea why and how to fix it? Thanks!

**Comment by donadigo** [comment]
As far as I remember I've added executable entry validation because without it, the entry would just not show in the app menu 
(not talking about AppEditor now) without having a valid executable path. It seems like GLib when reading the file, doesn't add it to the app info list when it doesn't have a valid executable.

**Comment by TingPing** [comment]
The desktop-file-spec has a `TryExec` field that will only show if the executable exists. If glib is applying that logic to all `Exec` fields that sounds like a bug to me.

**Pull request merged**
